### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by TomOrth** [SouthEugeneRoboticsTeam/robot-maker#2]
Not 100% sure but afaik, Windows does not support bash scripts so a batch file would also need to be provided for windows programmers to use this tool

**Comment by SUPERCILEX** [comment]
@atf1999 No need, any reasonable Windows developer has the [Git Bash](https://git-for-windows.github.io/) and it fully supports bash scripts. I've used it before tons of times to automate stuff.

**Comment by andrewda** [comment]
@SUPERCILEX could you test if this works on Git Bash for Windows when you get a chance?

**Comment by TomOrth** [comment]
@SUPERCILEX I was unaware that git bash supported bash scripts.  I mainly use linux and only recently have been doing development on a Windows machine. Thank you for clarifying.

**Comment by andrewda** [comment]
Alright, this should _hopefully_ work on Git Bash or Cygwin now as of 911e0c75a4811ecaa8f842307f677e6b872b0e02.
